//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUTEClassAdministrationClient.ClassAdministrationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/BUTEClassAdministrationTypes", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/BUTEClassAdministrationTypes", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, BUTEClassAdministrationClient.ClassAdministrationServiceReference.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/BUTEClassAdministrationTypes", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/BUTEClassAdministrationTypes", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, BUTEClassAdministrationClient.ClassAdministrationServiceReference.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/BUTEClassAdministrationTypes", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClassAdministrationServiceReference.IClassAdministrationService")]
    public interface IClassAdministrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/CreateStudents", ReplyAction="http://tempuri.org/IClassAdministrationService/CreateStudentsResponse")]
        void CreateStudents(BUTEClassAdministrationTypes.Student[] students);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/ReadStudentsFromSemester", ReplyAction="http://tempuri.org/IClassAdministrationService/ReadStudentsFromSemesterResponse")]
        BUTEClassAdministrationTypes.Student[] ReadStudentsFromSemester(string semester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/UpdateStudents", ReplyAction="http://tempuri.org/IClassAdministrationService/UpdateStudentsResponse")]
        void UpdateStudents(BUTEClassAdministrationTypes.Student[] students);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/DeleteStudent", ReplyAction="http://tempuri.org/IClassAdministrationService/DeleteStudentResponse")]
        void DeleteStudent(BUTEClassAdministrationTypes.Student[] students);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/CreateCourse", ReplyAction="http://tempuri.org/IClassAdministrationService/CreateCourseResponse")]
        void CreateCourse(BUTEClassAdministrationTypes.Course[] courses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/ReadCoursesFromSemester", ReplyAction="http://tempuri.org/IClassAdministrationService/ReadCoursesFromSemesterResponse")]
        BUTEClassAdministrationTypes.Course[] ReadCoursesFromSemester(string semester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/UpdateCourses", ReplyAction="http://tempuri.org/IClassAdministrationService/UpdateCoursesResponse")]
        void UpdateCourses(BUTEClassAdministrationTypes.Course[] courses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/DeleteCourses", ReplyAction="http://tempuri.org/IClassAdministrationService/DeleteCoursesResponse")]
        void DeleteCourses(BUTEClassAdministrationTypes.Course[] courses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/CreateGroup", ReplyAction="http://tempuri.org/IClassAdministrationService/CreateGroupResponse")]
        void CreateGroup(BUTEClassAdministrationTypes.Group[] groups);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/ReadGroupsFromSemester", ReplyAction="http://tempuri.org/IClassAdministrationService/ReadGroupsFromSemesterResponse")]
        BUTEClassAdministrationTypes.Group[] ReadGroupsFromSemester(string semester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/UpdateGroups", ReplyAction="http://tempuri.org/IClassAdministrationService/UpdateGroupsResponse")]
        void UpdateGroups(BUTEClassAdministrationTypes.Group[] groups);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/DeleteGroups", ReplyAction="http://tempuri.org/IClassAdministrationService/DeleteGroupsResponse")]
        void DeleteGroups(BUTEClassAdministrationTypes.Group[] groups);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/CreateInstructor", ReplyAction="http://tempuri.org/IClassAdministrationService/CreateInstructorResponse")]
        void CreateInstructor(BUTEClassAdministrationTypes.Instructor[] instructors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/ReadInstructors", ReplyAction="http://tempuri.org/IClassAdministrationService/ReadInstructorsResponse")]
        BUTEClassAdministrationTypes.Instructor[] ReadInstructors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/UpdateInstructors", ReplyAction="http://tempuri.org/IClassAdministrationService/UpdateInstructorsResponse")]
        void UpdateInstructors(BUTEClassAdministrationTypes.Instructor[] instructors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassAdministrationService/DeleteInstructors", ReplyAction="http://tempuri.org/IClassAdministrationService/DeleteInstructorsResponse")]
        void DeleteInstructors(BUTEClassAdministrationTypes.Instructor[] instructors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassAdministrationServiceChannel : BUTEClassAdministrationClient.ClassAdministrationServiceReference.IClassAdministrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassAdministrationServiceClient : System.ServiceModel.ClientBase<BUTEClassAdministrationClient.ClassAdministrationServiceReference.IClassAdministrationService>, BUTEClassAdministrationClient.ClassAdministrationServiceReference.IClassAdministrationService {
        
        public ClassAdministrationServiceClient() {
        }
        
        public ClassAdministrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassAdministrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassAdministrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassAdministrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateStudents(BUTEClassAdministrationTypes.Student[] students) {
            base.Channel.CreateStudents(students);
        }
        
        public BUTEClassAdministrationTypes.Student[] ReadStudentsFromSemester(string semester) {
            return base.Channel.ReadStudentsFromSemester(semester);
        }
        
        public void UpdateStudents(BUTEClassAdministrationTypes.Student[] students) {
            base.Channel.UpdateStudents(students);
        }
        
        public void DeleteStudent(BUTEClassAdministrationTypes.Student[] students) {
            base.Channel.DeleteStudent(students);
        }
        
        public void CreateCourse(BUTEClassAdministrationTypes.Course[] courses) {
            base.Channel.CreateCourse(courses);
        }
        
        public BUTEClassAdministrationTypes.Course[] ReadCoursesFromSemester(string semester) {
            return base.Channel.ReadCoursesFromSemester(semester);
        }
        
        public void UpdateCourses(BUTEClassAdministrationTypes.Course[] courses) {
            base.Channel.UpdateCourses(courses);
        }
        
        public void DeleteCourses(BUTEClassAdministrationTypes.Course[] courses) {
            base.Channel.DeleteCourses(courses);
        }
        
        public void CreateGroup(BUTEClassAdministrationTypes.Group[] groups) {
            base.Channel.CreateGroup(groups);
        }
        
        public BUTEClassAdministrationTypes.Group[] ReadGroupsFromSemester(string semester) {
            return base.Channel.ReadGroupsFromSemester(semester);
        }
        
        public void UpdateGroups(BUTEClassAdministrationTypes.Group[] groups) {
            base.Channel.UpdateGroups(groups);
        }
        
        public void DeleteGroups(BUTEClassAdministrationTypes.Group[] groups) {
            base.Channel.DeleteGroups(groups);
        }
        
        public void CreateInstructor(BUTEClassAdministrationTypes.Instructor[] instructors) {
            base.Channel.CreateInstructor(instructors);
        }
        
        public BUTEClassAdministrationTypes.Instructor[] ReadInstructors() {
            return base.Channel.ReadInstructors();
        }
        
        public void UpdateInstructors(BUTEClassAdministrationTypes.Instructor[] instructors) {
            base.Channel.UpdateInstructors(instructors);
        }
        
        public void DeleteInstructors(BUTEClassAdministrationTypes.Instructor[] instructors) {
            base.Channel.DeleteInstructors(instructors);
        }
    }
}
