//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace BUTEClassAdministrationTypes
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Instructor))]
    [KnownType(typeof(Course))]
    [KnownType(typeof(Room))]
    [KnownType(typeof(Student))]
    public partial class Group: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string Semester
        {
            get { return _semester; }
            set
            {
                if (_semester != value)
                {
                    _semester = value;
                    OnPropertyChanged("Semester");
                }
            }
        }
        private string _semester;
    
        [DataMember]
        public decimal Index
        {
            get { return _index; }
            set
            {
                if (_index != value)
                {
                    _index = value;
                    OnPropertyChanged("Index");
                }
            }
        }
        private decimal _index;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Instructor Instructor
        {
            get { return _instructor; }
            set
            {
                if (!ReferenceEquals(_instructor, value))
                {
                    var previousValue = _instructor;
                    _instructor = value;
                    FixupInstructor(previousValue);
                    OnNavigationPropertyChanged("Instructor");
                }
            }
        }
        private Instructor _instructor;
    
        [DataMember]
        public Course Course
        {
            get { return _course; }
            set
            {
                if (!ReferenceEquals(_course, value))
                {
                    var previousValue = _course;
                    _course = value;
                    FixupCourse(previousValue);
                    OnNavigationPropertyChanged("Course");
                }
            }
        }
        private Course _course;
    
        [DataMember]
        public Room Room
        {
            get { return _room; }
            set
            {
                if (!ReferenceEquals(_room, value))
                {
                    var previousValue = _room;
                    _room = value;
                    FixupRoom(previousValue);
                    OnNavigationPropertyChanged("Room");
                }
            }
        }
        private Room _room;
    
        [DataMember]
        public TrackableCollection<Student> Student
        {
            get
            {
                if (_student == null)
                {
                    _student = new TrackableCollection<Student>();
                    _student.CollectionChanged += FixupStudent;
                }
                return _student;
            }
            set
            {
                if (!ReferenceEquals(_student, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_student != null)
                    {
                        _student.CollectionChanged -= FixupStudent;
                    }
                    _student = value;
                    if (_student != null)
                    {
                        _student.CollectionChanged += FixupStudent;
                    }
                    OnNavigationPropertyChanged("Student");
                }
            }
        }
        private TrackableCollection<Student> _student;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Instructor = null;
            FixupInstructorKeys();
            Course = null;
            FixupCourseKeys();
            Room = null;
            FixupRoomKeys();
            Student.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupInstructor(Instructor previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Group.Contains(this))
            {
                previousValue.Group.Remove(this);
            }
    
            if (Instructor != null)
            {
                if (!Instructor.Group.Contains(this))
                {
                    Instructor.Group.Add(this);
                }
    
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Instructor")
                    && (ChangeTracker.OriginalValues["Instructor"] == Instructor))
                {
                    ChangeTracker.OriginalValues.Remove("Instructor");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Instructor", previousValue);
                }
                if (Instructor != null && !Instructor.ChangeTracker.ChangeTrackingEnabled)
                {
                    Instructor.StartTracking();
                }
                FixupInstructorKeys();
            }
        }
    
        private void FixupInstructorKeys()
        {
            const string IdKeyName = "Instructor.Id";
    
            if(ChangeTracker.ExtendedProperties.ContainsKey(IdKeyName))
            {
                if(Instructor == null ||
                   !Equals(ChangeTracker.ExtendedProperties[IdKeyName], Instructor.Id))
                {
                    ChangeTracker.RecordOriginalValue(IdKeyName, ChangeTracker.ExtendedProperties[IdKeyName]);
                }
                ChangeTracker.ExtendedProperties.Remove(IdKeyName);
            }
        }
    
        private void FixupCourse(Course previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Group.Contains(this))
            {
                previousValue.Group.Remove(this);
            }
    
            if (Course != null)
            {
                if (!Course.Group.Contains(this))
                {
                    Course.Group.Add(this);
                }
    
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Course")
                    && (ChangeTracker.OriginalValues["Course"] == Course))
                {
                    ChangeTracker.OriginalValues.Remove("Course");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Course", previousValue);
                }
                if (Course != null && !Course.ChangeTracker.ChangeTrackingEnabled)
                {
                    Course.StartTracking();
                }
                FixupCourseKeys();
            }
        }
    
        private void FixupCourseKeys()
        {
            const string IdKeyName = "Course.Id";
    
            if(ChangeTracker.ExtendedProperties.ContainsKey(IdKeyName))
            {
                if(Course == null ||
                   !Equals(ChangeTracker.ExtendedProperties[IdKeyName], Course.Id))
                {
                    ChangeTracker.RecordOriginalValue(IdKeyName, ChangeTracker.ExtendedProperties[IdKeyName]);
                }
                ChangeTracker.ExtendedProperties.Remove(IdKeyName);
            }
        }
    
        private void FixupRoom(Room previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.Group, this))
            {
                previousValue.Group = null;
            }
    
            if (Room != null)
            {
                Room.Group = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Room")
                    && (ChangeTracker.OriginalValues["Room"] == Room))
                {
                    ChangeTracker.OriginalValues.Remove("Room");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Room", previousValue);
                }
                if (Room != null && !Room.ChangeTracker.ChangeTrackingEnabled)
                {
                    Room.StartTracking();
                }
                FixupRoomKeys();
            }
        }
    
        private void FixupRoomKeys()
        {
            const string IdKeyName = "Room.Id";
    
            if(ChangeTracker.ExtendedProperties.ContainsKey(IdKeyName))
            {
                if(Room == null ||
                   !Equals(ChangeTracker.ExtendedProperties[IdKeyName], Room.Id))
                {
                    ChangeTracker.RecordOriginalValue(IdKeyName, ChangeTracker.ExtendedProperties[IdKeyName]);
                }
                ChangeTracker.ExtendedProperties.Remove(IdKeyName);
            }
        }
    
        private void FixupStudent(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Student item in e.NewItems)
                {
                    item.Group = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Student", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Student item in e.OldItems)
                {
                    if (ReferenceEquals(item.Group, this))
                    {
                        item.Group = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Student", item);
                    }
                }
            }
        }

        #endregion
    }
}
