//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "HallgatoKurzus", "Hallgato", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Database_Design.Hallgato), "Kurzus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Database_Design.Kurzus))]
[assembly: EdmRelationshipAttribute("Model", "CsoportGyakorlatvezeto", "Csoport", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Database_Design.Csoport), "Gyakorlatvezeto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Database_Design.Gyakorlatvezeto))]
[assembly: EdmRelationshipAttribute("Model", "KurzusCsoport", "Kurzus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Database_Design.Kurzus), "Csoport", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Database_Design.Csoport))]
[assembly: EdmRelationshipAttribute("Model", "TeremKurzus", "Terem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Database_Design.Terem), "Kurzus", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Database_Design.Kurzus))]
[assembly: EdmRelationshipAttribute("Model", "CsoportTerem", "Csoport", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Database_Design.Csoport), "Terem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Database_Design.Terem))]
[assembly: EdmRelationshipAttribute("Model", "CsoportHallgato", "Csoport", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Database_Design.Csoport), "Hallgato", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Database_Design.Hallgato))]

#endregion

namespace Database_Design
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TerembeosztoEntitasok : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TerembeosztoEntitasok object using the connection string found in the 'TerembeosztoEntitasok' section of the application configuration file.
        /// </summary>
        public TerembeosztoEntitasok() : base("name=TerembeosztoEntitasok", "TerembeosztoEntitasok")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TerembeosztoEntitasok object.
        /// </summary>
        public TerembeosztoEntitasok(string connectionString) : base(connectionString, "TerembeosztoEntitasok")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TerembeosztoEntitasok object.
        /// </summary>
        public TerembeosztoEntitasok(EntityConnection connection) : base(connection, "TerembeosztoEntitasok")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hallgato> HallgatoSet
        {
            get
            {
                if ((_HallgatoSet == null))
                {
                    _HallgatoSet = base.CreateObjectSet<Hallgato>("HallgatoSet");
                }
                return _HallgatoSet;
            }
        }
        private ObjectSet<Hallgato> _HallgatoSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Terem> TeremSet
        {
            get
            {
                if ((_TeremSet == null))
                {
                    _TeremSet = base.CreateObjectSet<Terem>("TeremSet");
                }
                return _TeremSet;
            }
        }
        private ObjectSet<Terem> _TeremSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Gyakorlatvezeto> GyakorlatvezetoSet
        {
            get
            {
                if ((_GyakorlatvezetoSet == null))
                {
                    _GyakorlatvezetoSet = base.CreateObjectSet<Gyakorlatvezeto>("GyakorlatvezetoSet");
                }
                return _GyakorlatvezetoSet;
            }
        }
        private ObjectSet<Gyakorlatvezeto> _GyakorlatvezetoSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Csoport> CsoportSet
        {
            get
            {
                if ((_CsoportSet == null))
                {
                    _CsoportSet = base.CreateObjectSet<Csoport>("CsoportSet");
                }
                return _CsoportSet;
            }
        }
        private ObjectSet<Csoport> _CsoportSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kurzus> KurzusSet
        {
            get
            {
                if ((_KurzusSet == null))
                {
                    _KurzusSet = base.CreateObjectSet<Kurzus>("KurzusSet");
                }
                return _KurzusSet;
            }
        }
        private ObjectSet<Kurzus> _KurzusSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HallgatoSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHallgatoSet(Hallgato hallgato)
        {
            base.AddObject("HallgatoSet", hallgato);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TeremSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeremSet(Terem terem)
        {
            base.AddObject("TeremSet", terem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GyakorlatvezetoSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGyakorlatvezetoSet(Gyakorlatvezeto gyakorlatvezeto)
        {
            base.AddObject("GyakorlatvezetoSet", gyakorlatvezeto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CsoportSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCsoportSet(Csoport csoport)
        {
            base.AddObject("CsoportSet", csoport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KurzusSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKurzusSet(Kurzus kurzus)
        {
            base.AddObject("KurzusSet", kurzus);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Csoport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Csoport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Csoport object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="felev">Initial value of the Felev property.</param>
        /// <param name="sorszam">Initial value of the Sorszam property.</param>
        public static Csoport CreateCsoport(global::System.Int32 id, global::System.String felev, global::System.Decimal sorszam)
        {
            Csoport csoport = new Csoport();
            csoport.Id = id;
            csoport.Felev = felev;
            csoport.Sorszam = sorszam;
            return csoport;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Felev
        {
            get
            {
                return _Felev;
            }
            set
            {
                OnFelevChanging(value);
                ReportPropertyChanging("Felev");
                _Felev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Felev");
                OnFelevChanged();
            }
        }
        private global::System.String _Felev;
        partial void OnFelevChanging(global::System.String value);
        partial void OnFelevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Sorszam
        {
            get
            {
                return _Sorszam;
            }
            set
            {
                OnSorszamChanging(value);
                ReportPropertyChanging("Sorszam");
                _Sorszam = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sorszam");
                OnSorszamChanged();
            }
        }
        private global::System.Decimal _Sorszam;
        partial void OnSorszamChanging(global::System.Decimal value);
        partial void OnSorszamChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CsoportGyakorlatvezeto", "Gyakorlatvezeto")]
        public Gyakorlatvezeto Gyakorlatvezeto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gyakorlatvezeto>("Model.CsoportGyakorlatvezeto", "Gyakorlatvezeto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gyakorlatvezeto>("Model.CsoportGyakorlatvezeto", "Gyakorlatvezeto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Gyakorlatvezeto> GyakorlatvezetoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gyakorlatvezeto>("Model.CsoportGyakorlatvezeto", "Gyakorlatvezeto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Gyakorlatvezeto>("Model.CsoportGyakorlatvezeto", "Gyakorlatvezeto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "KurzusCsoport", "Kurzus")]
        public Kurzus Kurzus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kurzus>("Model.KurzusCsoport", "Kurzus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kurzus>("Model.KurzusCsoport", "Kurzus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kurzus> KurzusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kurzus>("Model.KurzusCsoport", "Kurzus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kurzus>("Model.KurzusCsoport", "Kurzus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CsoportTerem", "Terem")]
        public Terem Terem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terem>("Model.CsoportTerem", "Terem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terem>("Model.CsoportTerem", "Terem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Terem> TeremReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terem>("Model.CsoportTerem", "Terem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Terem>("Model.CsoportTerem", "Terem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CsoportHallgato", "Hallgato")]
        public EntityCollection<Hallgato> Hallgato
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hallgato>("Model.CsoportHallgato", "Hallgato");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hallgato>("Model.CsoportHallgato", "Hallgato", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Gyakorlatvezeto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gyakorlatvezeto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Gyakorlatvezeto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="neptun">Initial value of the Neptun property.</param>
        /// <param name="nev">Initial value of the Nev property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Gyakorlatvezeto CreateGyakorlatvezeto(global::System.Int32 id, global::System.String neptun, global::System.String nev, global::System.String email)
        {
            Gyakorlatvezeto gyakorlatvezeto = new Gyakorlatvezeto();
            gyakorlatvezeto.Id = id;
            gyakorlatvezeto.Neptun = neptun;
            gyakorlatvezeto.Nev = nev;
            gyakorlatvezeto.Email = email;
            return gyakorlatvezeto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Neptun
        {
            get
            {
                return _Neptun;
            }
            set
            {
                OnNeptunChanging(value);
                ReportPropertyChanging("Neptun");
                _Neptun = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Neptun");
                OnNeptunChanged();
            }
        }
        private global::System.String _Neptun;
        partial void OnNeptunChanging(global::System.String value);
        partial void OnNeptunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nev
        {
            get
            {
                return _Nev;
            }
            set
            {
                OnNevChanging(value);
                ReportPropertyChanging("Nev");
                _Nev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nev");
                OnNevChanged();
            }
        }
        private global::System.String _Nev;
        partial void OnNevChanging(global::System.String value);
        partial void OnNevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CsoportGyakorlatvezeto", "Csoport")]
        public EntityCollection<Csoport> Csoport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Csoport>("Model.CsoportGyakorlatvezeto", "Csoport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Csoport>("Model.CsoportGyakorlatvezeto", "Csoport", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Hallgato")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hallgato : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hallgato object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="neptun">Initial value of the Neptun property.</param>
        /// <param name="nev">Initial value of the Nev property.</param>
        /// <param name="felev">Initial value of the Felev property.</param>
        public static Hallgato CreateHallgato(global::System.Int32 id, global::System.String neptun, global::System.String nev, global::System.String felev)
        {
            Hallgato hallgato = new Hallgato();
            hallgato.Id = id;
            hallgato.Neptun = neptun;
            hallgato.Nev = nev;
            hallgato.Felev = felev;
            return hallgato;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Neptun
        {
            get
            {
                return _Neptun;
            }
            set
            {
                OnNeptunChanging(value);
                ReportPropertyChanging("Neptun");
                _Neptun = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Neptun");
                OnNeptunChanged();
            }
        }
        private global::System.String _Neptun;
        partial void OnNeptunChanging(global::System.String value);
        partial void OnNeptunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nev
        {
            get
            {
                return _Nev;
            }
            set
            {
                OnNevChanging(value);
                ReportPropertyChanging("Nev");
                _Nev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nev");
                OnNevChanged();
            }
        }
        private global::System.String _Nev;
        partial void OnNevChanging(global::System.String value);
        partial void OnNevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Felev
        {
            get
            {
                return _Felev;
            }
            set
            {
                OnFelevChanging(value);
                ReportPropertyChanging("Felev");
                _Felev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Felev");
                OnFelevChanged();
            }
        }
        private global::System.String _Felev;
        partial void OnFelevChanging(global::System.String value);
        partial void OnFelevChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "HallgatoKurzus", "Kurzus")]
        public Kurzus Kurzus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kurzus>("Model.HallgatoKurzus", "Kurzus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kurzus>("Model.HallgatoKurzus", "Kurzus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kurzus> KurzusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kurzus>("Model.HallgatoKurzus", "Kurzus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kurzus>("Model.HallgatoKurzus", "Kurzus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CsoportHallgato", "Csoport")]
        public Csoport Csoport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Csoport>("Model.CsoportHallgato", "Csoport").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Csoport>("Model.CsoportHallgato", "Csoport").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Csoport> CsoportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Csoport>("Model.CsoportHallgato", "Csoport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Csoport>("Model.CsoportHallgato", "Csoport", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Kurzus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kurzus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kurzus object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="felev">Initial value of the Felev property.</param>
        /// <param name="het_napja">Initial value of the Het_napja property.</param>
        /// <param name="het_paritasa">Initial value of the Het_paritasa property.</param>
        /// <param name="idosav_kezdete">Initial value of the Idosav_kezdete property.</param>
        public static Kurzus CreateKurzus(global::System.Int32 id, global::System.String felev, global::System.Decimal het_napja, global::System.Boolean het_paritasa, global::System.TimeSpan idosav_kezdete)
        {
            Kurzus kurzus = new Kurzus();
            kurzus.Id = id;
            kurzus.Felev = felev;
            kurzus.Het_napja = het_napja;
            kurzus.Het_paritasa = het_paritasa;
            kurzus.Idosav_kezdete = idosav_kezdete;
            return kurzus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Felev
        {
            get
            {
                return _Felev;
            }
            set
            {
                OnFelevChanging(value);
                ReportPropertyChanging("Felev");
                _Felev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Felev");
                OnFelevChanged();
            }
        }
        private global::System.String _Felev;
        partial void OnFelevChanging(global::System.String value);
        partial void OnFelevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Het_napja
        {
            get
            {
                return _Het_napja;
            }
            set
            {
                OnHet_napjaChanging(value);
                ReportPropertyChanging("Het_napja");
                _Het_napja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Het_napja");
                OnHet_napjaChanged();
            }
        }
        private global::System.Decimal _Het_napja;
        partial void OnHet_napjaChanging(global::System.Decimal value);
        partial void OnHet_napjaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Het_paritasa
        {
            get
            {
                return _Het_paritasa;
            }
            set
            {
                OnHet_paritasaChanging(value);
                ReportPropertyChanging("Het_paritasa");
                _Het_paritasa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Het_paritasa");
                OnHet_paritasaChanged();
            }
        }
        private global::System.Boolean _Het_paritasa;
        partial void OnHet_paritasaChanging(global::System.Boolean value);
        partial void OnHet_paritasaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Idosav_kezdete
        {
            get
            {
                return _Idosav_kezdete;
            }
            set
            {
                OnIdosav_kezdeteChanging(value);
                ReportPropertyChanging("Idosav_kezdete");
                _Idosav_kezdete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Idosav_kezdete");
                OnIdosav_kezdeteChanged();
            }
        }
        private global::System.TimeSpan _Idosav_kezdete;
        partial void OnIdosav_kezdeteChanging(global::System.TimeSpan value);
        partial void OnIdosav_kezdeteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "HallgatoKurzus", "Hallgato")]
        public EntityCollection<Hallgato> Hallgato
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hallgato>("Model.HallgatoKurzus", "Hallgato");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hallgato>("Model.HallgatoKurzus", "Hallgato", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "KurzusCsoport", "Csoport")]
        public EntityCollection<Csoport> Csoport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Csoport>("Model.KurzusCsoport", "Csoport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Csoport>("Model.KurzusCsoport", "Csoport", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "TeremKurzus", "Terem")]
        public EntityCollection<Terem> Terem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Terem>("Model.TeremKurzus", "Terem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Terem>("Model.TeremKurzus", "Terem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Terem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Terem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Terem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nev">Initial value of the Nev property.</param>
        /// <param name="gepek_szama">Initial value of the Gepek_szama property.</param>
        /// <param name="ulohelyek_szama">Initial value of the Ulohelyek_szama property.</param>
        public static Terem CreateTerem(global::System.Int32 id, global::System.String nev, global::System.Int32 gepek_szama, global::System.Decimal ulohelyek_szama)
        {
            Terem terem = new Terem();
            terem.Id = id;
            terem.Nev = nev;
            terem.Gepek_szama = gepek_szama;
            terem.Ulohelyek_szama = ulohelyek_szama;
            return terem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nev
        {
            get
            {
                return _Nev;
            }
            set
            {
                OnNevChanging(value);
                ReportPropertyChanging("Nev");
                _Nev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nev");
                OnNevChanged();
            }
        }
        private global::System.String _Nev;
        partial void OnNevChanging(global::System.String value);
        partial void OnNevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Gepek_szama
        {
            get
            {
                return _Gepek_szama;
            }
            set
            {
                OnGepek_szamaChanging(value);
                ReportPropertyChanging("Gepek_szama");
                _Gepek_szama = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gepek_szama");
                OnGepek_szamaChanged();
            }
        }
        private global::System.Int32 _Gepek_szama;
        partial void OnGepek_szamaChanging(global::System.Int32 value);
        partial void OnGepek_szamaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Ulohelyek_szama
        {
            get
            {
                return _Ulohelyek_szama;
            }
            set
            {
                OnUlohelyek_szamaChanging(value);
                ReportPropertyChanging("Ulohelyek_szama");
                _Ulohelyek_szama = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ulohelyek_szama");
                OnUlohelyek_szamaChanged();
            }
        }
        private global::System.Decimal _Ulohelyek_szama;
        partial void OnUlohelyek_szamaChanging(global::System.Decimal value);
        partial void OnUlohelyek_szamaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "TeremKurzus", "Kurzus")]
        public EntityCollection<Kurzus> Kurzus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kurzus>("Model.TeremKurzus", "Kurzus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kurzus>("Model.TeremKurzus", "Kurzus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CsoportTerem", "Csoport")]
        public Csoport Csoport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Csoport>("Model.CsoportTerem", "Csoport").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Csoport>("Model.CsoportTerem", "Csoport").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Csoport> CsoportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Csoport>("Model.CsoportTerem", "Csoport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Csoport>("Model.CsoportTerem", "Csoport", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
